export const MS_PER_SECOND = 1000;

export const UI_ACTION_DENIED_CAMERA_SHAKE_DURATION_MS = 220;
export const UI_ACTION_DENIED_CAMERA_SHAKE_AMPLITUDE = 0.09;
export const UI_ACTION_DENIED_CAMERA_SHAKE_FREQ_X = 83;
export const UI_ACTION_DENIED_CAMERA_SHAKE_FREQ_Y = 71;
export const UI_ACTION_DENIED_CAMERA_SHAKE_FREQ_Z = 79;
export const UI_ACTION_DENIED_CAMERA_SHAKE_SCALE_XZ = 0.5;
export const UI_ACTION_DENIED_CAMERA_SHAKE_SCALE_Y = 0.22;

export const UI_ACTION_DENIED_HUD_SHAKE_DURATION_SEC = 0.22;

export const UI_ACTION_DENIED_HUD_SHAKE_TRANSLATE_PX = 1;
export const UI_ACTION_DENIED_HUD_SHAKE_ROTATE_DEG = 0.25;
export const UI_ACTION_DENIED_HUD_SHAKE_ROTATE_DEG_KEYFRAME_75_SCALE = 0.8;

export const UI_ACTION_DENIED_SFX_NOISE_DURATION_SEC = 0.12;
export const UI_ACTION_DENIED_SFX_NOISE_PLACEHOLDER_FREQ_HZ = 120;
/** Relative SFX volume (0–100) for `UI_ACTION_DENIED` in audio config. */
export const UI_ACTION_DENIED_SFX_VOLUME = 45;

export const TOWER_SHOP_MONEY_ICON_SIZE_PX = 16;
